tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install -g @angular/cli
      rm /tmp/.npm-lock
    command: ''
  - init: sleep 5 && while [ -f /tmp/.npm-lock ]; do sleep 5; done
    command:  ng serve --open
image:
  file: .gitpod.Dockerfile
